spring.application.name=session13
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/supply_management
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.jpa.open-in-view=false

spring.jackson.mapper.sort-properties-alphabetically=false
spring.jackson.deserialization.fail-on-unknown-properties=true

logging.level.root=INFO

logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicExtractor=OFF

logging.level.com.medical.service=TRACE
logging.file.name=logs/supply_management.log
logging.logback.rollingpolicy.max-file-size=2MB
logging.logback.rollingpolicy.file-name-pattern=logs/supply_management.%d{yyyy-MM-dd}.%i.log.gz
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.total-size-cap=50MB